# Generated by Django 4.2.1 on 2023-06-06 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paymentMehod',
            new_name='paymentMethod',
        ),
    ]
